services:
  - type: web
    name: product-management-api
    runtime: docker
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_KEY
        generateValue: true
      - key: ALLOW_ORIGIN
        sync: false
